blog/urls.py
from . import views
from django.urls import path,include
from .feeds import LatestPostsFeed

app_name = "blog"

urlpatterns = [
    path('', views.PostIndex, name='index'),
    path('tag/<str:tag_slug>',views.PostIndex,name='index_tag'),
    path('category/<str:cat_slug>',views.PostIndex,name='index_category'),
    path('<str:slug>/', views.PostDetail, name='single'),
    path("feed/rss", LatestPostsFeed(), name="feed"),
]

booking_app/urls.py
from django.urls import path,include
from . import views

app_name = 'booking_app'

urlpatterns = [
    path('',views.index,name='index'),
    path('delete/<int:id>',views.delete,name='delete'),   
    path('add',views.add_,name='add'),
    path('edit/<int:id>',views.edit,name='edit'),
]

temp_site/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings
from django.contrib.sitemaps.views import sitemap
from blog.sitemaps import PostSitemap
from website.sitemaps import StaticViewSitemap
from django.views.generic import TemplateView
from django.conf.urls import (
    handler400, handler403, handler404, handler500
)

sitemaps = {
    "posts": PostSitemap,
    "static": StaticViewSitemap,
}
urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('website.urls', namespace='website')),
    path('blog/', include('blog.urls', namespace='blog')),
    path('booking_app/', include('booking_app.urls', namespace='booking_app')),
    path('ckeditor/', include('ckeditor_uploader.urls')),
    path("sitemap.xml", sitemap, {"sitemaps": sitemaps}, name="sitemap"),
    path('djga/', include('google_analytics.urls')),
    path('robots.txt', include('robots.urls')),
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

handler400 = 'website.views.error_400'  # bad_request
handler403 = 'website.views.error_403'  # permission_denied
handler404 = 'website.views.error_404'  # page_not_found
handler500 = 'website.views.error_500'  # server_error

booking_app/models.py
from django.db import models

# Create your models here.

class HelthDepartment(models.Model):
    name = models.CharField(max_length=100)
    availability = models.DateTimeField()
    def __str__(self):
        return self.name

#helth_department = ((0,"daily task"),(1,"work jobs"),(2,"house needs"))

class Patient(models.Model):
    name = models.CharField(max_length=100)
    contact = models.CharField(max_length=100)
    email = models.EmailField()
    booking_date = models.DateTimeField(auto_now_add=True,blank=True,null=True)
    appointment_date = models.DateTimeField(null=True , blank=True)
    #appointment_time = models.TimeField(null=True , blank=True)
    helth_department = models.ForeignKey(HelthDepartment,on_delete=models.CASCADE,null=True) 
    history = models.TextField()
    #patient_contact = models.PhoneField()
    #helth_department = models.PositiveSmallIntegerField(choices=helth_department,default=0)


    def __str__(self):
        return self.name

    class Meta:
        ordering = ["-booking_date"]

booking_app/forms.py
from .models import Patient
from django import forms


class DateInput(forms.DateInput):
    input_type = 'date'

class TimeInput(forms.TimeInput):
    input_type = 'time'
class PatientForm (forms.ModelForm):
    class Meta : 
        model = Patient
        fields = '__all__'
        widgets = {
            'appointment_date': DateInput(),
            #'appointment_time': TimeInput(),
        }
    

booking_app/views.py
from django.http import HttpResponse,HttpResponseRedirect
from . models import HelthDepartment , Patient
from . forms import PatientForm
from django.shortcuts import render,redirect,get_object_or_404
#import requests



# Create your views here.
# Retrieve
def index(request):
    #categories = Category.objects.all()
    helthDepartments=HelthDepartment.objects.all()
    patients = Patient.objects.all()
    form = PatientForm()
    context = {"form":form}
    return render(request, "booking_app/index.html",context)

    # Delete
def delete(request,id):
    patient = Patient.objects.get(id=id)
    patient.delete()
    return HttpResponseRedirect(request.META.get('HTTP_REFERER'))

# update
def edit(request,id):
    patients = Patient.objects.all()
    #selected_patient = patients.objects.get(id=id)
    selected_patient = get_objects_or_404(Patient,id=id)
    if request.method == "GET":   
        form = PatientForm(instance=selected_patient)
        context = {"patients":patients,"form":form ,"selected_patient":selected_patient}
        return render(request,"edit.html",context)
    if request.method == "POST":
        form = PatientForm(request.POST)
        if form.is_valid:
            #print(form.__dict__)
            selected_patient.name = form.data["name"]
            selected_patient.contact = form.data["contact"]
            selected_patient.email = form.data["email"]
            selected_patient. booking_date = form.data[" booking_date"]
            selected_patient.appointment_date = form.data["appointment_date"]
            selected_patient.helth_department = form.data["helth_department"]
            selected_patient.history = form.data["historyl"]
            selected_patient.save()
       
        return redirect("/")





# Insert
def add_(request):
    if request.method=="POST":
        form = PatientForm(data=request.POST)
        if form.is_valid():
            
            form.save()
    return render (request, "website/index.html")       

templates/booking_app/edit.html
<h3>Booking Appointment</h3>
<ul>
  {% for patient in patients %}
  <li>
    {{patient.name}} - {{patient.contact}} - {{Patient.email}} - {{Patient.booking_date}} - {{Patient.appointment_date}} - {{Patient.helth_department }} - {{Patient.history }}
  </li>
  <a onclick="myFunction('{{patient.id}}')">Delete </a>
  <a  href="{% url 'booking_app:edit' id=patient.id %}" >Edit </a>

  {% endfor %}
</ul>
<form action="{% url 'booking_app:edit' id=selected_patient.id %}" method="post">
  {% csrf_token %} {{form.as_p}}

  <button type="submit">Send</button>
  <a  href="{% url 'booking_app:index' %}">Cancel</a>
</form>

<script>
    function myFunction(patient_id) {
        var r = confirm("sure you want to delete?");
        if (r == true) {
            console.log(patient_id);
            console.log("yes");
            const url = "http://127.0.0.1:8000/delete/"+patient_id
            const Http = new XMLHttpRequest();
            Http.open("GET", url);
            Http.send();

            Http.onreadystatechange = (e) => {console.log(Http.responseText)}
            //window.location.replace("http://127.0.0.1:8000");
        } 
        //window.location.href = "/";
    }
</script>

templates/booking_app/index.html
{% extends "base.html" %} {% load static %}
{% block content %}
<style>
    input, #id_email {
        color : red;
    }
</style>
<!--
<html>
  <head>
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
    <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js" integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js" integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM" crossorigin="anonymous"></script>
  </head>
<h3>Booking Appointment</h3>
<ul>
  {% for patient in patients %}
  <li>
    {{patient.name}} - {{patient.contact}} - {{Patient.email}} - {{Patient.booking_date}} - {{Patient.appointment_date}} - {{Patient.helth_department }} - {{Patient.history }}
  </li>

<a onclick="myFunction('{{patient.id}}')">Delete </a>
<a  href="{% url 'booking_app:edit' id=patient.id %}" >Edit </a>

{% endfor %}
</ul>
<form action="{% url 'booking_app:add' %}" method="post">
{% csrf_token %} {{form.as_p}}
<input type="datetime-local" id="birthdaytime" name="birthdaytime">
<button type="submit">Send</button>
<a  href="{% url 'booking_app:index' %}">Cancel</a>
</form>

<script>
  function myFunction(patient_id) {
      var r = confirm("sure you want to delete?");
      if (r == true) {
          console.log(patient_id);
          console.log("yes");
          const url = "http://127.0.0.1:8000/delete/"+patient_id
          const Http = new XMLHttpRequest();
          Http.open("GET", url);
          Http.send();

          Http.onreadystatechange = (e) => {console.log(Http.responseText)}
          //window.location.replace("http://127.0.0.1:8000");
      } 
      //window.location.href = "/";
  }
</script>
</html>
-->
	<!-- Start Appointment -->
	<div id="appointment" class="appointment-main">
		<div class="container">
			<div class="row">
				<div class="col-lg-12">
					<div class="title-box">
						<h2>Appointment</h2>
						<p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. </p>
					</div>
				</div>
			</div>
			<div class="row">
				<div class="col-lg-6 col-md-6">
					<div class="well-block">
                        <div class="well-title">
                            <h2>Book an Appointment</h2>
                        </div>
                       
                            <!-- Form start -->
                            <form action="{% url 'booking_app:add' %}" method="post">
                            {% csrf_token %}
                            <div class="row">
                                <div class="col-md-6">
                                    <div class="form-group">
                                        <label class="control-label" for="name">Name</label>
                                        <input id="name" name="name" type="text" placeholder="Name" class="form-control input-md">
                                    </div>
                                </div>
                                <!-- Form start -->
                                <div class="col-md-6">
                                  <div class="form-group">
                                      <label class="control-label" for="name">Contact</label>
                                      <input id="contact" name="contact" type="text" placeholder="Contac" class="form-control input-md">
                                  </div>
                              </div>
                              <!-- Form start 
                              <div class="col-md-6">
                                <div class="form-group">
                                    <label class="control-label" for="name">Booking Date</label>
                                    <input id="booking_date" name="booking_date" type="text" placeholder="Booking Date" class="form-control input-md">
                                </div>
                            </div>-->
                                <!-- Text input-->
                                <div class="col-md-6">
                                    <div class="form-group">
                                        <label class="control-label" for="email">Email</label>
                                        <input id="email" name="email" type="text" placeholder="E-Mail" class="form-control input-md">
                                    </div>
                                </div>
                                <!-- Text input-->
                                <div class="col-md-6">
                                    <div class="form-group">
                                        <label class="control-label" for="date">Appointment Date</label>
                                       <!-- <input id="appointment_date" name="appointment_date" type="text" placeholder="Appointment Date" class="form-control input-md">-->
                                       {{form.appointment_date}}
                                    </div>
                                </div>
                                <!-- Select Basic -->
                                <!-- 
                                <div class="col-md-6">
                                    <div class="form-group">
                                        <label class="control-label" for="time">Appointment Time</label>
                                        <select id="appointment_time" name="appointment_time" class="form-control">
                                            <option value="8:00 to 9:00">8:00 to 9:00</option>
                                            <option value="9:00 to 10:00">9:00 to 10:00</option>
                                            <option value="10:00 to 1:00">10:00 to 1:00</option>
                                        </select>
                                    </div>
                                </div>
                                -->
                                <!-- Text input -->
                                <div class="col-md-6">
                                  <div class="form-group">
                                      <label class="control-label" for="name">History</label>
                                      <input id="history" name="history" type="text" placeholder="History " class="form-control input-md">
                                  </div>
                                </div>
                            
                                <!-- Select Basic --> 
                                <div class="col-md-12">
                                    <div class="form-group">
                                        <label class="control-label" for="appointmentfor">Helth Department</label>
                                        <select id="helth_department" name="helth_department" class="form-control">
                                            {% for x, y in form.fields.helth_department.choices %}
                                                <option value="{{ x }}">{{ y }}</option>
                    
                                            {% endfor %}
                                        </select>
                                    </div>
                                </div>
                                    
                                <!-- Button -->
                                <div class="col-md-12">
                                    <div class="form-group">
                                        <button id="singlebutton" name="singlebutton" class="new-btn-d br-2">Make An Appointment</button>
                                    </div>
                                </div>
                            </div>
                        </form>


                        
          
                        <!-- form end -->
                       
                    </div>
				</div>
				<div class="col-lg-6 col-md-6">
					<div class="well-block">
                        <div class="well-title">
                            <h2>Why Appointment with Us</h2>
                        </div>
                        <div class="feature-block">
                            <div class="feature feature-blurb-text">
                                <h4 class="feature-title">24/7 Hours Available</h4>
                                <div class="feature-content">
                                    <p>Integer nec nisi sed mi hendrerit mattis. Vestibulum mi nunc, ultricies quis vehicula et, iaculis in magnestibulum.</p>
                                </div>
                            </div>
                            <div class="feature feature-blurb-text">
                                <h4 class="feature-title">Experienced Staff Available</h4>
                                <div class="feature-content">
                                    <p>Aliquam sit amet mi eu libero fermentum bibendum pulvinar a turpis. Vestibulum quis feugiat risus. </p>
                                </div>
                            </div>
                            <div class="feature feature-blurb-text">
                                <h4 class="feature-title">Low Price & Fees</h4>
                                <div class="feature-content">
                                    <p>Praesent eu sollicitudin nunc. Cras malesuada vel nisi consequat pretium. Integer auctor elementum nulla suscipit in.</p>
                                </div>
                            </div>
                        </div>
                    </div>
				</div>
			</div>
		</div>
	</div>
  <!-- End Appointment -->
  {% endblock content %}