blog/urls.py
from . import views
from django.urls import path,include
from .feeds import LatestPostsFeed

app_name = "blog"

urlpatterns = [
    path('', views.PostIndex, name='index'),
    path('tag/<str:tag_slug>',views.PostIndex,name='index_tag'),
    path('category/<str:cat_slug>',views.PostIndex,name='index_category'),
    path('<str:slug>/', views.PostDetail, name='single'),
    path("feed/rss", LatestPostsFeed(), name="feed"),
]

temp_site/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings
from django.contrib.sitemaps.views import sitemap
from blog.sitemaps import PostSitemap
from website.sitemaps import StaticViewSitemap
from django.views.generic import TemplateView
from django.conf.urls import (
    handler400, handler403, handler404, handler500
)

sitemaps = {
    "posts": PostSitemap,
    "static": StaticViewSitemap,
}
urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('website.urls', namespace='website')),
    path('blog/', include('blog.urls', namespace='blog')),
    path('booking_app/', include('booking_app.urls', namespace='booking_app')),
    path('ckeditor/', include('ckeditor_uploader.urls')),
    path("sitemap.xml", sitemap, {"sitemaps": sitemaps}, name="sitemap"),
    path('djga/', include('google_analytics.urls')),
    path('robots.txt', include('robots.urls')),
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

handler400 = 'website.views.error_400'  # bad_request
handler403 = 'website.views.error_403'  # permission_denied
handler404 = 'website.views.error_404'  # page_not_found
handler500 = 'website.views.error_500'  # server_error

website/urls.py
from . import views
from django.urls import path

app_name = "website"

urlpatterns = [
    path('', views.index, name='index'),
    path('contact', views.contact_view, name='contact'),
    path('about', views.about_view, name='about'),
    path('privacy', views.privacy, name='privacy'),
    path('rules', views.rules, name='rules'),
    
]

website/models.py
from django.db import models
from django.contrib.auth.models import User
from django.conf import settings
from datetime import datetime, timedelta, timezone, tzinfo
from ckeditor_uploader.fields import RichTextUploadingField
from taggit.managers import TaggableManager
from django.urls import reverse
from io import BytesIO
from PIL import Image
from django.core.files import File
from django.utils.http import urlunquote
from imagekit.models import ImageSpecField
from pilkit.processors import Thumbnail
from django.utils import timezone
from django.utils.html import strip_spaces_between_tags, strip_tags
from django.utils.text import Truncator
from meta.models import ModelMeta


STATUS = ((0, "Draft"), (1, "Publish"))


class Ticket(models.Model):
    '''
    ticket_CHOICES = (
		(1, 'ارتباط با ما'),
		(2, 'دوره های آنلاین'),
        (3, 'سفارش پروژه'),
	)
    '''
    name = models.CharField(max_length=200)
    #family_name = models.CharField(max_length=200,null=True)
    email = models.EmailField(default=None)
    phone_number = models.CharField(max_length=200,blank=True)
    subject =  models.CharField(max_length=200,null=True)
    #ticket_type = models.PositiveSmallIntegerField(choices=ticket_CHOICES,default=1,blank=True)
    body = models.TextField()
    #checked = models.BooleanField(default=False)
    created_date = models.DateTimeField(auto_now_add=True)
    #updated_date = models.DateTimeField(auto_now=True)

    class Meta:
        ordering = ['-created_date']

    def __str__(self):
        return self.name

website/views.py
from blog.models import Post
from .form import ContactForm
from django.http import HttpResponse
from django.shortcuts import render, get_object_or_404
from django.http import HttpResponseRedirect
from django.contrib import messages
from django.contrib.auth.decorators import login_required
from taggit.models import Tag
from django.utils.http import urlunquote
from meta.views import Meta
from paginator.utils import paginate

# root page
def index(request):
    meta = Meta(
        title="کنترل ارتباطات هوشمند آریا",
        description='آموزش های مبتنی بر اینترنت اشیا و هوش مصنوعی به زبان پایتون و طراحی سایت های مبتنی بر Django',
        keywords=['طراحی سایت', 'هوش مصنوعی', 'اینترنت اشیا','آموزش'],
        locale= 'fa_IR',
        url = request.build_absolute_uri() ,
        twitter_site= "icc-aria",
        schemaorg_title = "کنترل ارتباطات هوشمند آریا",
        
    )

    return render(request, "website/index.html",{"meta":meta})


def contact_view(request):
    meta = Meta(
        title="ارتباط با ما",
        description='راتباط با ما و مشاوره در حوزه های مختلف فناوری',
        keywords=['طراحی سایت', 'هوش مصنوعی', 'اینترنت اشیا','مشاوره'],
        locale= 'fa_IR',
        url = request.build_absolute_uri() ,
        twitter_site= "icc-aria"
    )
    
    if request.method == "POST":
        form = ContactForm(data=request.POST)
        if form.is_valid():
            form.save()
            messages.success(request, 'your ticket has been recieved')
            return HttpResponseRedirect(request.path_info)
        else:
            messages.error(request, 'wew have got an error')
            return HttpResponse(status=400)
            #return HttpResponseRedirect(request.path_info)
    else:
        contactform = ContactForm()
        context = {"form": contactform,"meta":meta}
        return render(request, "website/contact.html", context)
    


def about_view(request):
    meta = Meta(
        title="درباره ما",
        description='ما پایتون، هوش مصنوعی و هوش تجاری را در کنار هم به کار بردیم تا یک پلتفرم شگفت انگیز اینترنت اشیا بسازیم، امیدواریم که لذت ببرید',
        keywords=['طراحی سایت', 'هوش مصنوعی', 'اینترنت اشیا','آموزش'],
        locale= 'fa_IR',
        url = request.build_absolute_uri() ,
        twitter_site= "icc-aria"
    )
    return render(request, "website/about.html",{"meta":meta})


def privacy(request):
    meta = Meta(
        title="حریم خصوصی",
        description='کنترل ارتباطات هوشمند آریا در راستای حفظ امنیت و حریم خصوصی کاربران خود اعلام می کند که از هرگونه اطلاعات وارد شده توسط کاربران اعم از ایمیل، پیام هاو هرگونه اطلاعات شخصی، محافظت کرده و به هیچ عنوان این اطلاعات را در اختیار سازمان ها و مراکز دیگر به منظور تبلیغات با خدمات دیگر ارائه ندهد',
        keywords=['نحوه استفاده', 'استفاده', 'قوانین'],
        locale= 'fa_IR',
        url = request.build_absolute_uri() ,
        twitter_site= "icc-aria"
    )
    return render(request, "website/privacy.html",{"meta":meta})


def rules(request):
    meta = Meta(
        title="شرایط استفاده",
        description='دانشجویان و برنامه نویسان عزیز، لطفا به هنگام شرکت در دوره ها و استفاده از مطالب، موارد زیر را رعایت فرمایید .',
        keywords=['شرایط استفاده','قوانین'],
        locale= 'fa_IR',
        url = request.build_absolute_uri() ,
        twitter_site= "icc-aria"
    )
    return render(request, "website/rules.html",{"meta":meta})

def error_400(request, exception):
    context = {'exeption': exception}
    response = render(request, "errors/400.html", context=context)
    response.status_code = 400
    return response


def error_403(request, exception):
    context = {'exeption': exception}
    response = render(request, "errors/403.html", context=context)
    response.status_code = 403
    return response


def error_404(request, exception):
    context = {'exeption': exception}
    response = render(request, "errors/404.html", context=context)
    response.status_code = 404
    return response


def error_500(request):
    context = {}
    response = render(request, "errors/500.html", context=context)
    response.status_code = 500
    return response

templates/website/about.html
{% extends "base.html" %} {% load static %}
{% block content %}
	<!-- Start About us -->
	<div id="about" class="about-box">
		<div class="about-a1">
			<div class="container">
				<div class="row">
					<div class="col-lg-12">
						<div class="title-box">
							<h2>About Us</h2>
							<p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. </p>
						</div>
					</div>
				</div>
				<div class="row">
					<div class="col-lg-12 col-md-12 col-sm-12">
						<div class="row align-items-center about-main-info">
							<div class="col-lg-6 col-md-6 col-sm-12">
								<h2> Welcome to Health Lab </h2>
								<p>Fusce convallis ante id purus sagittis malesuada. Sed erat ipsum, suscipit sit amet auctor quis, vehicula ut leo. Maecenas felis nulla, tincidunt ac blandit a, consectetur quis elit. Nulla ut magna eu purus cursus sagittis. Praesent fermentum tincidunt varius. Proin sit amet tempus magna. Fusce pellentesque vulputate urna. </p>
								<p>Fusce convallis ante id purus sagittis malesuada. Sed erat ipsum, suscipit sit amet auctor quis, vehicula ut leo. Maecenas felis nulla, tincidunt ac blandit a, consectetur quis elit. Nulla ut magna eu purus cursus sagittis. Praesent fermentum tincidunt varius. Proin sit amet tempus magna. Fusce pellentesque vulputate urna. </p>
								<a href="#" class="new-btn-d br-2">Read More</a>
							</div>
							<div class="col-lg-6 col-md-6 col-sm-12">
								<div class="about-m">
									<ul id="banner">
										<li>
											<img src="{% static 'img/about-img-01.jpg' %}" alt="">
										</li>
										<li>
											<img src="{% static 'img/about-img-02.jpg' %}" alt="">
										</li>
										<li>
											<img src="{% static 'img/about-img-03.jpg' %}" alt="">
										</li>
									</ul>
								</div>
							</div>
						</div>
					</div>
				</div>
			</div>
		</div>
	</div>
	<!-- End About us -->
{% endblock content %}

templates/website/contact.html
{% extends "base.html" %} {% load static %}
{% block content %}
<!-- Start Contact -->
<div id="contact" class="contact-box">
    <div class="container">
        <div class="row">
            <div class="col-lg-12">
                <div class="title-box">
                    <h2>Contact us</h2>
                    <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. </p>
                </div>
            </div>
        </div>
        <div class="row">
            
            <div class="col-lg-12 col-xs-12">
              <div class="contact-block">
                <form class="form-contact contact_form" action="{% url 'website:contact' %}" method="post">
                    {% csrf_token %} 
                    <div class="row">
                        <div class="col-12">
                            <div class="form-group">
                                <textarea class="form-control w-100" name="body" id="id_body" cols="30" rows="9" onfocus="this.placeholder = ''" onblur="this.placeholder = 'Enter Message'" placeholder=" Enter Message"></textarea>
                            </div>
                        </div>
                        <div class="col-sm-6">
                            <div class="form-group">
                                <input class="form-control valid" name="name" id="id_name" type="text" onfocus="this.placeholder = ''" onblur="this.placeholder = 'Enter your name'" placeholder="Enter your name">
                            </div>
                        </div>
                        <div class="col-sm-6">
                            <div class="form-group">
                                <input class="form-control valid" name="email" id="id_email" type="email" onfocus="this.placeholder = ''" onblur="this.placeholder = 'Enter email address'" placeholder="Email">
                            </div>
                        </div>
                        <div class="col-sm-6">
                            <div class="form-group">
                                <input class="form-control valid" name="phone_number" id="id_phone_number" type="text" onfocus="this.placeholder = ''" onblur="this.placeholder = 'Enter your phone number'" placeholder="Enter your phone number">
                            </div>
                        </div>
                        <div class="col-sm-6">
                            <div class="form-group">
                                <input class="form-control valid" name="subject" id="id_subject" type="text" onfocus="this.placeholder = ''" onblur="this.placeholder = 'Enter subject'" placeholder="Enter subject">
                            </div>
                        </div>
                        
                    </div>
                    <div class="form-group mt-3">
                        <button type="submit" class="button button-contactForm boxed-btn">Send</button>
                    </div>
                </form>
              </div>
            </div>
            <div class="col-lg-12 col-xs-12">
                <div class="left-contact">
                    <h2>Address</h2>
                    <div class="media cont-line">
                        <div class="media-left icon-b">
                            <i class="fa fa-location-arrow" aria-hidden="true"></i>
                        </div>
                        <div class="media-body dit-right">
                            <h4>Address</h4>
                            <p>Fleming 196 Woodside Circle Mobile, FL 36602</p>
                        </div>
                    </div>
                    <div class="media cont-line">
                        <div class="media-left icon-b">
                            <i class="fa fa-envelope" aria-hidden="true"></i>
                        </div>
                        <div class="media-body dit-right">
                            <h4>Email</h4>
                            <a href="#">demoinfo@gmail.com</a><br>
                            <a href="#">demoinfo@gmail.com</a>
                        </div>
                    </div>
                    <div class="media cont-line">
                        <div class="media-left icon-b">
                            <i class="fa fa-volume-control-phone" aria-hidden="true"></i>
                        </div>
                        <div class="media-body dit-right">
                            <h4>Phone Number</h4>
                            <a href="#">12345 67890</a><br>
                            <a href="#">12345 67890</a>
                        </div>
                    </div>
                </div>
                </div>
            
            
            
        </div>
    </div>
</div>
<!-- End Contact -->
{% endblock content %}

templates/website/index.html
{% extends "base.html" %} {% load static %}
{% block content %}
	<!-- Start Banner -->
	<div class="ulockd-home-slider">
		<div class="container-fluid">
			<div class="row">
				<div class="pogoSlider" id="js-main-slider">
					<div class="pogoSlider-slide" data-transition="fade" data-duration="1500" style="background-image:url({% static 'img/slider-01.jpg' %});">
						<div class="lbox-caption pogoSlider-slide-element">
							<div class="lbox-details">
								<h1>Welcome to Health Lab</h1>
								<p>Fusce convallis ante id purus sagittis malesuada. Sed erat ipsum </p>
								<a href="#" class="btn">Contact Us</a>
							</div>
						</div>
					</div>
					<div class="pogoSlider-slide" data-transition="fade" data-duration="1500" style="background-image:url({% static 'img/slider-02.jpg' %});">
						<div class="lbox-caption pogoSlider-slide-element">
							<div class="lbox-details">
								<h1>We are Expert in The Field of Health Lab</h1>
								<p>Fusce convallis ante id purus sagittis malesuada. Sed erat ipsum</p>
								<a href="#appointment" class="btn">Appointment</a>
							</div>
						</div>
					</div>
					<div class="pogoSlider-slide" data-transition="fade" data-duration="1500" style="background-image:url({% static 'img/slider-03.jpg' %});">
						<div class="lbox-caption pogoSlider-slide-element">
							<div class="lbox-details">
								<h1>Welcome to Health Lab</h1>
								<p>Fusce convallis ante id purus sagittis malesuada. Sed erat ipsum </p>
								<a href="#" class="btn">Contact Us</a>
							</div>
						</div>
						
					</div>
				</div><!-- .pogoSlider -->
			</div>
		</div>
	</div>
	<!-- End Banner -->
{% endblock content %}

templates/website/privacy.html
{% extends "base.html" %} {% load static %}
{% load blog_tags %}


{% block styles %}

{% endblock styles %}



{% block content %}

{% endblock %}
{% block javascripts %}

{% endblock javascripts %}

templates/website/rules.html
{% extends "base.html" %} {% load static %}
{% load blog_tags %}


{% block styles %}

{% endblock styles %}



{% block content %}
{% endblock %}
{% block javascripts %}

{% endblock javascripts %}