blog/urls.py
from . import views
from django.urls import path,include
from .feeds import LatestPostsFeed

app_name = "blog"

urlpatterns = [
    path('', views.PostIndex, name='index'),
    path('tag/<str:tag_slug>',views.PostIndex,name='index_tag'),
    path('category/<str:cat_slug>',views.PostIndex,name='index_category'),
    path('<str:slug>/', views.PostDetail, name='single'),
    path("feed/rss", LatestPostsFeed(), name="feed"),
]

temp_site/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings
from django.contrib.sitemaps.views import sitemap
from blog.sitemaps import PostSitemap
from website.sitemaps import StaticViewSitemap
from django.views.generic import TemplateView
from django.conf.urls import (
    handler400, handler403, handler404, handler500
)

sitemaps = {
    "posts": PostSitemap,
    "static": StaticViewSitemap,
}
urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('website.urls', namespace='website')),
    path('blog/', include('blog.urls', namespace='blog')),
    path('booking_app/', include('booking_app.urls', namespace='booking_app')),
    path('ckeditor/', include('ckeditor_uploader.urls')),
    path("sitemap.xml", sitemap, {"sitemaps": sitemaps}, name="sitemap"),
    path('djga/', include('google_analytics.urls')),
    path('robots.txt', include('robots.urls')),
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

handler400 = 'website.views.error_400'  # bad_request
handler403 = 'website.views.error_403'  # permission_denied
handler404 = 'website.views.error_404'  # page_not_found
handler500 = 'website.views.error_500'  # server_error

website/urls.py
from . import views
from django.urls import path

app_name = "website"

urlpatterns = [
    path('', views.index, name='index'),
    path('contact', views.contact_view, name='contact'),
    path('about', views.about_view, name='about'),
    path('privacy', views.privacy, name='privacy'),
    path('rules', views.rules, name='rules'),
    
]

templates/base.html
{% load static %}
{% load meta %}
{% load google_analytics_tags %}

<!DOCTYPE html>
<html lang="en"> {% meta_namespaces_schemaorg %}><!-- Basic -->
    <head {% meta_namespaces %}>
        {% include "meta/meta.html" %} {% block title %} {% endblock title %}
        <meta charset="utf-8">
        <meta http-equiv="X-UA-Compatible" content="IE=edge">   
    
        <!-- Mobile Metas -->
        <meta name="viewport" content="width=device-width, minimum-scale=1.0, maximum-scale=1.0, user-scalable=no">
    
        <!-- Site Metas -->
        <title>Health Lab - Responsive HTML5 Template</title>  
        <meta name="keywords" content="">
        <meta name="description" content="">
        <meta name="author" content="">

        <!-- Site Icons -->
        <link rel="shortcut icon" href="{% static 'img/favicon.ico' %}" type="image/x-icon">
        <link rel="apple-touch-icon" href="{% static 'img/apple-touch-icon.png' %}">

        <!-- Bootstrap CSS -->
        <link rel="stylesheet" href="{% static 'css/bootstrap.min.css' %}">
        <!-- Pogo Slider CSS -->
        <link rel="stylesheet" href="{% static 'css/pogo-slider.min.css' %}">
        <!-- Site CSS -->
        <link rel="stylesheet" href="{% static 'css/style.css' %}">    
        <!-- Responsive CSS -->
        <link rel="stylesheet" href="{% static 'css/responsive.css' %}">
        <!-- Custom CSS -->
        <link rel="stylesheet" href="{% static 'css/custom.css' %}">

        <!--[if lt IE 9]>
        <script src="https://oss.maxcdn.com/libs/html5shiv/3.7.0/html5shiv.js"></script>
        <script src="https://oss.maxcdn.com/libs/respond.js/1.4.2/respond.min.js"></script>
        <![endif]-->
        {% block styles %} {% endblock styles %}
    </head>
    <body id="home" data-spy="scroll" data-target="#navbar-wd" data-offset="98">

        <!-- LOADER -->
        <!-- <div id="preloader">
            <div class="loader">
                <img src="{% static 'img//preloader.gif" alt="" />
            </div>
        </div>end loader -->
        <!-- END LOADER -->

        
        <!-- Start header -->
        <header class="top-header">
            <nav class="navbar header-nav navbar-expand-lg">
                <div class="container">
                    <a class="navbar-brand" href="{% url 'website:index' %}"><img src="{% static 'img/logo.png' %}" alt="image"></a>
                    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbar-wd" aria-controls="navbar-wd" aria-expanded="false" aria-label="Toggle navigation">
                        <span></span>
                        <span></span>
                        <span></span>
                    </button>
                    <div class="collapse navbar-collapse justify-content-end" id="navbar-wd">
                        <ul class="navbar-nav">
                            <li><a href="{% url 'website:index' %}">Home</a></li>
                            <li><a href="{% url 'website:about' %}">About Us</a></li>
                            <li><a href="{% url 'website:contact' %}">Contact</a></li>
                            <li><a href="{% url 'booking_app:index' %}">Book Appointment</a></li>
                            <li><a href="{% url 'blog:index' %}">Services</a></li>
                            
                        </ul>
                    </div>
                </div>
            </nav>
        </header>
        <!-- End header -->
        
        
        {% block content %} {% endblock content %}

        

        
            <!-- Start Footer -->
        <footer class="footer-box">
            <div class="container">
                <div class="row">
                    <div class="col-lg-12">
                        <p class="footer-company-name">All Rights Reserved. &copy; 2018 <a href="#">Health Lab</a> Design By : <a href="https://html.design/">html design</a></p>
                    </div>
                </div>
            </div>
        </footer>
        <!-- End Footer -->
        
        <a href="#" id="scroll-to-top" class="new-btn-d br-2"><i class="fa fa-angle-up"></i></a>




        

       
        <!-- ALL JS FILES -->
        <script src="{% static 'js/jquery.min.js' %}"></script>
        <script src="{% static 'js/popper.min.js' %}"></script>
        <script src="{% static 'js/bootstrap.min.js' %}"></script>
        <!-- ALL PLUGINS -->
        <script src="{% static 'js/jquery.magnific-popup.min.js' %}"></script>
        <script src="{% static 'js/jquery.pogo-slider.min.js' %}"></script> 
        <script src="{% static 'js/slider-index.js' %}"></script>
        <script src="{% static 'js/smoothscroll.js' %}"></script>
        <script src="{% static 'js/TweenMax.min.js' %}"></script>
        <script src="{% static 'js/main.js' %}"></script>
        <script src="{% static 'js/owl.carousel.min.js' %}"></script>
        <script src="{% static 'js/form-validator.min.js' %}"></script>
        <script src="{% static 'js/contact-form-script.js' %}"></script>
        <script src="{% static 'js/isotope.min.js' %}"></script>	
        <script src="{% static 'js/images-loded.min.js' %}"></script>	
        <script src="{% static 'js/custom.js' %}"></script>
        {% block javascripts %} {% endblock javascripts %}

    </body>
</html>